export default {
  ic_user: require('../Assets/icons/ic_user.png'),
  ic_close: require('../Assets/icons/ic_close.png'),
  ic_camera: require('../Assets/icons/ic_camera.png'),
  ic_plus: require('../Assets/icons/ic_plus.png'),
  ic_arrow_down: require('../Assets/icons/ic_arrow_down.png'),
  ic_check_box: require('../Assets/icons/ic_check_box.png'),
  ic_empty_check_box: require('../Assets/icons/ic_empty_check_box.png'),
  ic_rotate_left: require('../Assets/icons/ic_rotate_left.png'),
  ic_rotate_right: require('../Assets/icons/ic_rotate_right.png'),
  ic_home: require('../Assets/icons/ic_home.png'),
  ic_keyboard: require('../Assets/icons/ic_keyboard.png'),
  ic_color_background: require('../Assets/icons/ic_color_background.png'),
  ic_left_arrow: require('../Assets/icons/ic_left_arrow.png'),
  ic_color_text: require('../Assets/icons/ic_color_text.png'),
};
